# docker-compose.yml
version: '3.9'

services:
  hydra:
    container_name: hydra
    image: ghcr.io/hydradatabase/hydra:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - hydradb:/var/lib/postgresql/data
    restart: unless-stopped

  cloudbeaver:
    container_name: dbeaver
    image: dbeaver/cloudbeaver:latest
    ports:
      - ${DBEAVER_PORT}:8978
    volumes:
      - cloudbeaverdb:/opt/cloudbeaver/workspace
    restart: unless-stopped

# define volumes
volumes:
  hydradb:
    # uncomment if you want to use a local directory
    # driver: local
    # driver_opts:
    #   type: none
    #   device: ../../data/hydradatabase
    #   o: bind

  cloudbeaverdb:
    # uncomment if you want to use a local directory
    # driver: local
    # driver_opts:
    #   type: none
    #   device: ../../data/cloudbeaver
    #   o: bind
